- type: startingGear
  id: RadioGuardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack
    shoes: ClothingShoesBootsLaceup
    id: SyndiListeningPostPDA
    ears: ClothingHeadsetAltSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWebUnremoveable

- type: entity
  categories: [ HideSpawnMenu ]
  parent: ClothingOuterVestWeb
  id: ClothingOuterVestWebUnremoveable
  name: grafted web vest
  suffix: Unremoveable
  description: An off-the-shelf web vest that has been cruelly grafted onto its wearers body
  components:
  - type: Unremoveable
